# Generated by Django 5.0.9 on 2024-12-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('four_digit_code', models.CharField(max_length=4, unique=True)),
                ('employee_role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_date', models.DateField()),
                ('change_time', models.TimeField()),
                ('changed_by', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punch_in_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('absence_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('absence_type', models.CharField(max_length=50)),
                ('absence_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punch_in_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MilesLog',
            fields=[
                ('miles_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('week_id', models.CharField(max_length=50)),
                ('miles_date', models.DateField()),
                ('miles_driven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punch_in_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('punch_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_id', models.CharField(max_length=50)),
                ('record_date', models.DateField()),
                ('punch_in_time', models.TimeField(blank=True, null=True)),
                ('punch_out_time', models.TimeField(blank=True, null=True)),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punch_in_app.employee')),
            ],
            options={
                'db_table': 'PunchRecord',
            },
        ),
        migrations.CreateModel(
            name='WeekLog',
            fields=[
                ('week_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('week_ending_day', models.DateField()),
                ('total_hours', models.FloatField()),
                ('overtime', models.FloatField()),
                ('weighted_hours', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punch_in_app.employee')),
            ],
        ),
    ]
